# Generated by Django 6.0 on 2026-01-06 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0003_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='test_cases',
            field=models.TextField(blank=True),
        ),
    ]
