# Generated by Django 5.2.10 on 2026-02-02 16:51

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0006_project_file_alter_project_name_alter_project_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='project',
            unique_together={('user', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='usagemetric',
            unique_together={('user', 'project', 'date')},
        ),
    ]
